#!/bin/bash

# This file is licensed under the GNU Lesser General Public License v3.0
# See https://www.gnu.org/licenses/lgpl-3.0.txt for a copy of the license
#
# Usage: buildgpg config-file [step-num]

function printUsage {
  echo "Usage: $0 config-file [step-num]"
}


ABI=64     ## default is 64-bit build
LIBS_FILE=libs.txt
set -o pipefail


if [ "$1" = "-h" -o "$1" = "--help" ]; then
  printUsage
  exit
fi

if [ $# -lt 1 ]; then
  printUsage
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "Cannot find config file '$1'"
  exit 1
fi

source "$1"


# internal variables
PINENTRY=0.9.4
BASEDIR=$(dirname $0)
NCPU=$(sysctl hw.ncpu | awk '{print $2}')

if [ "${BASEDIR:0:1}" != "/" ]; then
  # ensure that BASEDIR is an absolute path
  BASEDIR=$(pwd)"/$BASEDIR"
fi
mkdir "$MAIN_DIR"
exec &> >(tee -a "$MAIN_DIR/create_gpg.log")


echo -n "Build started at "; date


step=0

if [ $# -gt 1 ]; then
  step=$2
fi

case $ABI in
32)
  ARCH="i386"
  HOSTSYSTEM="-host=i386-apple-darwin8.0.0"
  ;;
64)
  ARCH="x86_64"
  HOSTSYSTEM=""
  ;;
*)
  echo "Invalid ABI '$ABI'"
  exit 1
esac


function doFail {
  echo ""
  echo " ** ERROR at step $1 **   - build failed"
  echo ""
  exit 1
}

function unpack {
  inFile=$1
  fn=`echo $inFile|sed -E 's/^.*\.tar//'`

  case $fn in
  .lz)
	  lunzip=lunzip
	  if ! command -v lunzip &>/dev/null; then
		  lunzip="lzip -d"
	  fi
      ($lunzip -k -c $inFile | tar xf -) || doFail $inFile
      ;;
  .bz2)
    (tar jxf $inFile) || doFail $inFile
    ;;
  .gz|.xz)
    (tar zxf $inFile) || doFail $inFile
    ;;
  *)
    doFail $inFile
  esac
}

function buildlib {
  echo ""
  echo "**** building $2 ****"
  echo ""

  libname=${lib/-[0-9]*}
  moreParams=$(grep $libname $BASEDIR/config-params.txt | cut -d: -f2)
  n_cpu=$(grep $libname $BASEDIR/config-params.txt | cut -d: -f3)

  if [ "$moreParams" = "ignore" ]; then
    return 0
  fi

  if [ n_cpu = "" ]; then
    n_cpu=$NCPU
  fi

  if [ ! -f "configure" ]; then
    ./autogen.sh
  fi

  moreCFlags="$ADDITIONAL_CFLAGS"
  if [ ${libname:0:6} = "sqlite" ]; then
    moreCFlags=
  fi

  if [ ${libname:0:7} = "gettext" ]; then
    n_cpu=1
  fi
  

  CFLAGS="-arch $ARCH -m$ABI -ULOCALEDIR -DLOCALEDIR=\\\"${TARGET_DIR}/share/locale\\\" $moreCFlags" \
    CXXFLAGS="-arch $ARCH" \
    ABI=$ABI \
    LDFLAGS="-L$DIST_DIR/lib -arch $ARCH" \
    CPPFLAGS="-I$DIST_DIR/include -arch $ARCH" \
    PKG_CONFIG_PATH=$DIST_DIR/lib/pkgconfig \
    ./configure --prefix=$DIST_DIR \
    $HOSTSYSTEM $moreParams || doFail $1

  make -j $n_cpu && make install
  if [ $? -ne 0 ]; then
    echo ""
    echo "==> Build of $2 failed"
    doFail $1
  fi
}

# check if pkg-config is installed
if [ -z $(type -p pkg-config) ]; then
  echo "ERROR: pkg-config is not installed. This script requires pkg-config to be available."
  echo "Please fix your setup and try again."
  doFail 0
fi

if [ $step -le 1 ]; then
  echo "Downloading required files"
  mkdir -p $SRC_DIR
  cd $SRC_DIR
  for l in $(cat $BASEDIR/$LIBS_FILE); do
    libFull=$(echo $l | cut -d '|' -f 1)
    libF=$(basename $libFull)
    if [ ! -f $libF ]; then
      curl -L -o $libF $libFull
    else
      echo "Skipping $libFull"
    fi

    if [ ! -z "$libF" -a -f "$libF" ]; then
      # SHA-1 checksum check
      shsum1=$(echo $l | cut -d '|' -f 2)
	  algo=1
	  if [[ ${#shsum1} -eq 64 ]]; then
		  algo=256
	  fi
      shsum2=$(shasum -a $algo $libF | cut -d ' ' -f 1)
      if [ ! -z "$shsum1" -a "$shsum1" != "$shsum2" ]; then
        echo "SHA-1 sums of file $libF don't match"
        echo "expected: $shsum1"
        echo "obtained: $shsum2"
        doFail $step
      fi
    fi
  done
fi

if [ $step -le 4 ]; then
  cd $SRC_DIR
  gpgBaseName=$(basename $GPGDLPACKAGE)

  if [ ! -f $gpgBaseName ]; then
      echo "Downloading GnuPG"
      curl -L -o $gpgBaseName $GPGDLPACKAGE || doFail "Failed to download gpg"
  fi

  if [[ -n "$GPGDL_HASH" ]]; then
      shsum=$(shasum -a 256 $gpgBaseName | cut -d ' ' -f 1)
	  if [[ "$GPGDL_HASH" != "$shsum" ]]; then
          echo "SHA-1 sums of file $gpgBaseName don't match"
          echo "expected: $GPGDL_HASH"
          echo "obtained: $shsum"
		  doFail 4
	  fi
  else
	  if [ ! -f ${gpgBaseName}.sig ]; then
	      curl -L -o ${gpgBaseName}.sig ${GPGDLPACKAGE}.sig  || doFail "Failed to download gpg signature"
	  fi

	  stat=$(gpg2 --status-fd 1 --verify ${gpgBaseName}.sig ${gpgBaseName} | grep -c '^\[GNUPG:\] GOODSIG 249B39D24F25E3B6')

	  if [ $stat -eq 0 ]; then
	    echo "Could not verify GnuPG package signature"
	    echo "Please delete gpg package and signature file before retrying"
	    doFail 4
	  fi
  fi  
fi

if [ $step -le 6 ]; then
  echo "deleting build and dist directories"
  rm -rf $MAIN_PREFIX $DIST_DIR
fi


mkdir -p $MAIN_PREFIX
mkdir -p $DIST_DIR
cd $MAIN_PREFIX

if [ $step -le 8 ]; then
  for l in $(cat $BASEDIR/$LIBS_FILE); do
    libFull=$(echo $l | cut -d '|' -f 3)
    if [ -z "$libFull" ]; then
      libFull=$(echo $l | cut -d '|' -f 1)
    fi
    lib=`basename $libFull`
    if [ ! -z "$lib" -a -f "$SRC_DIR/$lib" ]; then
      echo "unpacking $lib"
      unpack $SRC_DIR/$lib || doFail 8
	  
	  
	  lib=$(basename $libFull | sed -E 's/.tar.(gz|bz2|xz|lz)//')
	  libname=${lib/-[0-9]*}
	  patches=( "${BASEDIR}/patches/${libname}/"*.patch )
	  if [[ -f "$patches" ]]; then
	      cd "$MAIN_PREFIX/$lib"
		  for patch in "${patches[@]}"; do
			  echo "Applying patch '$patch'"
			  patch -p1 -t -N < "$patch" || doFail 8
		  done
	  fi
	  
    fi
  done
fi

export PATH=$DIST_DIR/bin:$PATH

cstep=10
for l in $(cat $BASEDIR/$LIBS_FILE); do
  if [ $step -le $cstep ]; then
    libFull=$(echo $l | cut -d '|' -f 3)
    if [ -z "$libFull" ]; then
      libFull=$(echo $l | cut -d '|' -f 1)
    fi
    lib=$(basename $libFull | sed -E 's/.tar.(gz|bz2|xz|lz)//')
    if [ ! -z "$lib" -a -d "$MAIN_PREFIX/$lib" ]; then
      cd $MAIN_PREFIX/$lib
      make distclean > /dev/null 2>&1
      buildlib $cstep $lib
    fi
  fi
  cstep=$(expr $cstep + 1)
done


# Remove some unnecessary files.
if [[ $step -le 31 ]]; then
	rm -r "$DIST_DIR/share/man" "$DIST_DIR/share/locale" || doFail 31
fi




if [ $step -le 33 ]; then
  cd $MAIN_PREFIX
  tar jxf $SRC_DIR/gnupg-${GPGVERSION}.tar.bz2 || doFail 33
fi


cd $MAIN_PREFIX/gnupg-$GPGVERSION

if [ $step -le 34 ]; then
  ## apply version-specific patches to make gpg build properly (sometimes required)
  echo "checking patches"
  patch=${BASEDIR}/patches/gnupg-${GPGVERSION}.patch
  if [[ -f "$patch" ]]; then
	echo "Applying patch '$patch'"
    patch -p1 < "$patch" || doFail 34
  fi
  
  ## apply other patches
  patches=( "${BASEDIR}/patches/gnupg/"*.patch )
  if [[ -f "$patches" ]]; then
	  for patch in "${patches[@]}"; do
		  echo "Applying patch '$patch'"
		  patch -p1 -t -N < "$patch" || doFail 34
	  done
  fi
fi

## configure GnuPG

if [ $step -le 35 ]; then

  # ld does not support rpath on Mac (see below)

  export PATH=$BASE_DIR/bin:$PATH
  GPGCONFIGPARAM=""

  if [[ ! -f ./configure ]]; then
    GPGCONFIGPARAM="--enable-maintainer-mode"
    GETTEXT_PREFIX=$DIST_DIR/bin/ ./autogen.sh --force || doFail 35
  fi

  CFLAGS="-arch $ARCH $ADDITIONAL_CFLAGS -ULOCALEDIR -DLOCALEDIR=\\\"${TARGET_DIR}/share/locale\\\"" \
    CXXFLAGS="-arch $ARCH" \
    ABI=$ABI \
    LDFLAGS="-L$DIST_DIR/lib -arch $ARCH" \
    CPPFLAGS="-I$DIST_DIR/include -arch $ARCH" \
    PKG_CONFIG_PATH=$DIST_DIR/lib/pkgconfig \
    ./configure \
    --prefix=$DIST_DIR \
    --localstatedir=/var \
    --sysconfdir=${TARGET_DIR}/etc \
    $HOSTSYSTEM \
    --disable-rpath \
    --with-pinentry-pgm=${TARGET_DIR}/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac \
    --with-agent-pgm=${TARGET_DIR}/bin/gpg-agent \
    --with-scdaemon-pgm=${TARGET_DIR}/libexec/scdaemon \
    --with-dirmngr-pgm=${TARGET_DIR}/bin/dirmngr \
    --with-dirmngr-ldap-pgm=${TARGET_DIR}/libexec/dirmngr_ldap \
    --with-protect-tool-pgm=${TARGET_DIR}/libexec/gpg-protect-tool \
    --enable-gpg2-is-gpg \
    --with-libgpg-error-prefix=$DIST_DIR \
    --with-libgcrypt-prefix=$DIST_DIR \
    --with-libassuan-prefix=$DIST_DIR \
    --with-ksba-prefix=$DIST_DIR \
    --with-npth-prefix=$DIST_DIR \
    --with-readline=$DIST_DIR \
    --with-libintl-prefix=$DIST_DIR \
    $GPGCONFIGPARAM \
    --with-libiconv-prefix=$DIST_DIR || doFail 35
fi


if [ $step -le 40 ]; then
  make -j $NCPU || doFail 40
fi

if [ $step -le 42 ]; then
  make install || doFail 42
fi

# Adjust rpath using otool for binaries in bin/
if [ $step -le 45 ]; then
  # some files get wrong permissions, let's just fix them ...
  find $DIST_DIR -type f -exec chmod +w {} +

  cd $DIST_DIR/bin

  if [ -d gpg ]; then
    mv gpg/gpg gpg2
    rmdir gpg
  fi

  if [ -d gpgv ]; then
    mv gpgv/gpgv gpgv2
    rmdir gpgv
  fi


  for f in gpg gpgv gpg-agent gpg-connect-agent gpg-error gpgconf gpgparsemail gpgsm \
      gpgtar kbxutil watchgnupg dirmngr-client dirmngr mpicalc; do
    echo "adapting ld-paths for $f"
    install_name_tool -add_rpath @loader_path/../lib $f
    for l in `otool -L $f | cut -d' ' -f1`; do
      if [ `echo $l | grep -c "$DIST_DIR/lib"` -gt 0 ]; then
        b=@rpath/`basename $l`
        install_name_tool -change $l $b $f
      fi
    done
  done
fi

# Adjust rpath using otool for binaries in libexec/
if [ $step -le 47 ]; then
  cd $DIST_DIR/libexec
  for f in dirmngr_ldap gpg-preset-passphrase scdaemon gpg-check-pattern gpg-protect-tool gpg-wks-client; do
    echo "adapting ld-paths for $f"
    install_name_tool -add_rpath @loader_path/../lib $f
    for l in `otool -L $f | cut -d' ' -f1`; do
      if [ `echo $l | grep -c "$DIST_DIR/lib"` -gt 0 ]; then
        b=@rpath/`basename $l`
        install_name_tool -change $l $b $f
      fi
    done
  done
fi

if [ $step -le 50 ]; then
  rm -rf $REL_DIR >/dev/null 2>&1
  mkdir -p $REL_DIR
  cd $DIST_DIR

  tar cf - \
    bin/dirmngr \
    bin/dirmngr-client \
    bin/dumpsexp \
    bin/gpg-agent \
    bin/gpg-connect-agent \
    bin/gpg-error \
    bin/gpg \
    bin/gpgconf \
    bin/gpgparsemail \
    bin/gpgsm \
    bin/gpgtar \
    bin/gpgv \
    bin/hmac256 \
    bin/kbxutil \
    bin/mpicalc \
    bin/watchgnupg \
    lib/*dylib \
	libexec \
	share/gnupg \
	share/man \
	share/locale | (cd $REL_DIR; tar xf -)


  cd $REL_DIR/bin
  ln -s gpg gpg2

  cp $BASEDIR/scripts/convert-keyring .
fi



# Adjust rpath using otool for libraries in lib/
if [ $step -le 51 ]; then
  cd $REL_DIR/lib
  rm -f libgettext*
  for f in `find . -type f -name "*.dylib"`; do
    echo "adapting ld-paths for $f"
    install_name_tool -add_rpath @loader_path/../lib $f
    for l in `otool -L $f | cut -d' ' -f1`; do
      if [ `echo $l | grep -c "$DIST_DIR/lib"` -gt 0 ]; then
        b=@rpath/`basename $l`
        install_name_tool -change $l $b $f
      fi
    done
  done
fi

# Adjust ids using otool for libraries in lib/
if [ $step -le 52 ]; then
  cd $REL_DIR/lib
  for f in *.dylib; do
    if [ -f $f ] && [ ! -L $f ]; then
      echo "Adapting ID for $f"
      install_name_tool -id ${TARGET_DIR}/lib/$f $f
    fi
  done
fi

# ensure that all executables and libraries have correct lib-path settings
if [ $step -le 53 ]; then
  cd $REL_DIR

  otool -L $(ls -d bin/* | egrep -v '(convert-keyring|pinentry-mac.app)') | grep "$MAIN_DIR" && doFail 53.1
  otool -L libexec/* | grep "$MAIN_DIR" && doFail 53.2
  otool -L lib/* | grep "$MAIN_DIR" && doFail 53.3
fi




echo "done"
