name="MacGPG2"
appName=""

imgBackground="Installer/background_dmg.png"
rmName="Uninstall.app"
volumeLayout="Installer/DS_Store"


unset REVISION PRERELEASE

MAJOR=2
MINOR=0
REVISION=22

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
