name="MacGPG2"
appName=""

pkgProj_corename="${name}_Core.pkgproj"
pkgCoreName="${name}_Core.pkg"
pkgProj_name="${name}.pkgproj"
pkgName="${name}.pkg"

imgBackground="Installer/background_dmg.png"
volumeName="$name"
rmName="Uninstall.app"

unset REVISION PRERELEASE
MAJOR=2
MINOR=0
REVISION=19

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
