name="MacGPG2"
appName=""

imgBackground="Installer/background_dmg.png"
volumeName="$name"
rmName="Uninstall.app"

unset REVISION PRERELEASE
MAJOR=2
MINOR=0
REVISION=19

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
