#!/bin/sh

PROGRAM_NAME="gpg-agent"
LOGFILE="$HOME/Library/Logs/shutdown-gpg-agent.log"
AGENT_SOCKET_DEFAULT="$HOME/.gnupg/S.gpg-agent"
AGENT_SOCKET_ALT="/tmp/gpg-agent/$USER/S.gpg-agent"

log() {
    current_date=$(date "+%Y-%m-%d %H:%M:%S")
    echo "$current_date: $1"
    if [ "$2" != "" ]; then
        echo ""
    fi
}

onExit() {
    # Ignore future HUP, INT, and TERM signals: do not re-enter `onExit`.
    trap "" HUP INT TERM

    log "* Logout in progress..."
    if ! pid=$(pgrep "$PROGRAM_NAME"); then
        log "* $PROGRAM_NAME not running, no reason to kill it." 1
        return
    fi

    log "  - killing gpg-agent..."
    kill -9 $pid

    RET=$?

    # Remove the S.gpg-agent sockets, if present.
    for socket_path in "$AGENT_SOCKET_DEFAULT" "$AGENT_SOCKET_ALT"; do
        if [ -S "$socket_path" ]; then
            log "Removing S.gpg-agent sockets at $socket_path" 1
            rm -f "$socket_path" "$socket_path.ssh"
        fi
    done

    if [ "$RET" != "0" ]; then
        log "* Failed to kill $PROGRAM_NAME. Sorry..." 1
    else
        log "* Successfully killed $PROGRAM_NAME. job well done" 1
    fi

    exit 0
}

# Setting up the logfile.
exec >> $LOGFILE 2>&1

log "* Setting up kill event listeners"

# Setup the signals to trap which will invoke the onExit handler.
trap onExit HUP INT TERM

log "  - successfully setup kill event listeners"
log "  - waiting for logout..."
# Sleep for approx. a year. Every user should shutdown their computer at
# least once a year.
sleep 31536000 &
wait $!
