#!/bin/sh

macgpg=/usr/local/MacGPG2

# create CA trust store for gnutls
/usr/bin/security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain > /usr/local/gnupg-2.1/share/ca-certs.crt

# an existsting old link would have been overwritten with preinstall

cd /usr/local/bin
ln -s ../gnupg-2.1/bin/gpg2 gpg2
ln -s ../gnupg-2.1/bin/gpgsm gpgsm
ln -s ../gnupg-2.1/bin/gpgconf gpgconf

if [ $(grep -c 'MANPATH.*/usr/local/gnupg-2.1/share/man' /private/etc/man.conf) -eq 0 ]; then
  # Include man pages in global man pages
  cat >> /private/etc/man.conf <<EOT

MANPATH /usr/local/gnupg-2.1/share/man   ### Added by gnupg-2.1
EOT
fi

echo "/usr/local/gnupg-2.1/share/man" > /private/etc/manpaths.d/50-GnuPG-21

gpgTools=$(pkgutil --pkgs | grep '^org.gpgtools')

# kill all potentially pre-existing daemons
killall -kill gpg-agent scdaemon dirmngr


if [ "x$gpgTools" != "x" ]; then
  r=$(osascript -e '
set question to "Found an installation of GPG Tools (MacGPG2). We recommend you uninstall it to avoid compatibility issues between GnuPG 2.1 and GPGTools.\n\nDo you wan to uninstall GPG Tools?"
set cancel to "Ignore"
set uninst to "Uninstall GPG Tools"
activate
display dialog question buttons {cancel, uninst} default button uninst
')

  if [ $(echo $r | grep -c "Uninstall GPG Tools") -ne 0 ]; then

    launchctl stop org.gpgtools.Libmacgpg.xpc
    launchctl stop org.gpgtools.gpgmail.patch-uuid-user
    launchctl stop org.gpgtools.macgpg2.fix
    launchctl stop org.gpgtools.macgpg2.shutdown-gpg-agent
    launchctl stop org.gpgtools.macgpg2.updater
    launchctl stop org.gpgtools.macgpg2.gpg-agent

    launchctl remove org.gpgtools.Libmacgpg.xpc
    launchctl remove org.gpgtools.gpgmail.patch-uuid-user
    launchctl remove org.gpgtools.macgpg2.fix
    launchctl remove org.gpgtools.macgpg2.shutdown-gpg-agent
    launchctl remove org.gpgtools.macgpg2.updater
    launchctl remove org.gpgtools.macgpg2.gpg-agent

    cd /
    for pkg in $gpgTools; do
      pkgutil --only-files --files $pkg | tr '\n' '\0' | xargs -n 1 -0  rm -f
    done

    rm -rf /usr/local/MacGPG2

    # remove PKG information from OS X
    for f in $(pkgutil --pkgs | grep '^org.gpgtools'); do
      pkgutil --forget $f
    done
  fi
fi

exit 0  # unconditionally exit with "OK"
