#!/bin/sh

INSTDIR=/usr/local/gnupg-2.1
BINLINKS=/usr/local/bin/gpg /usr/local/bin/gpg2 /usr/local/bin/gpgsm /usr/local/bin/gpg-agent /usr/local/bin/gpg-connect-agent

if [ -d $INSTDIR ]; then
  rm -rf $INSTDIR
fi

if [ -e $INSTDIR ]; then
  rm -rf $INSTDIR
fi

for f in $BINLINKS; do

  if [ -L $f ]; then
    rm -f $f
  fi

  if [ -e $f ]; then
    mv -f $f ${f}.orig
  fi

done
