#!/bin/bash
# The post install MacGPG2 script for v2.0.17
# Copyright (c) Benjamin Donnachie 2011
# Released under GPL V3

PATH=/sbin:/bin:/usr/sbin:/usr/bin

OldMacGPG2="/usr/local"
MacGPG2="$OldMacGPG2/MacGPG2"

# Remove previous bad behaviour:

# Ascertain whether using obsolete login/out scripts and remove
defaults read com.apple.loginwindow LoginHook 2>&1  | grep --quiet "$OldMacGPG2/sbin/gpg-login.sh"  && defaults delete com.apple.loginwindow LoginHook
defaults read com.apple.loginwindow LogoutHook 2>&1 | grep --quiet "$OldMacGPG2/sbin/gpg-logout.sh" && defaults delete com.apple.loginwindow LogoutHook

# Now remove the gpg-agent helper AppleScript from login items:
osascript -e 'tell application "System Events" to delete login item "start-gpg-agent"' > /dev/null

# Iterate through each regular user account.
#  Remove any mention of gpg from environment.plist as per previous behaviour
#  Remove any sockets symlinks created by GPGTools
#  Check for invalid gpg.conf options
#  Check for invalid gpg-agent.conf options
#  Copy skeleton gpg.conf if not exist

for username in `dscl . -list /Users`
do
  # Get UID
  uniqueID=`dscl . -read /Users/$username UniqueID | awk '{ print $2 }'`
  
  # Only process regular accounts
  if [ $uniqueID -ge 500 ]; then
    homedir=`dscl . -read /Users/$username NFSHomeDirectory | awk '{ print $2 }'`
    primarygroup=`dscl . -read /Users/$username PrimaryGroupID | awk '{ print $2 }'`

    if [ -f "$homedir/.MacOSX/environment.plist" ]
      then
      defaults delete "$homedir/.MacOSX/environment" GPG_AGENT_INFO >& /dev/null
      # If ssh support enabled, remove associated entries
      grep --quiet "^enable-ssh-support" "$homedir/.gnupg/gpg-agent.conf"
      if [ $? -eq 0 ]
        then
        defaults delete "$homedir/.MacOSX/environment" SSH_AGENT_PID >& /dev/null
        defaults delete "$homedir/.MacOSX/environment" SSH_AUTH_SOCK >& /dev/null
      fi
    fi

    if [ -d "$homedir/.gnupg" ]; then 
      # Also clean up bad GPGTools behaviour:
      [ -h "$homedir/.gnupg/S.gpg-agent" ] && rm -f "$homedir/.gnupg/S.gpg-agent"
      [ -h "$homedir/.gnupg/S.gpg-agent.ssh" ] && rm -f "$homedir/.gnupg/S.gpg-agent.ssh"
    else
      mkdir "$homedir/.gnupg"
      chown $uniqueID:$primarygroup "$homedir/.gnupg"
      chmod og= "$homedir/.gnupg"
    fi

    if [ -e "$homedir/.gnupg/gpg.conf" ]; then
      # Bad gpg.conf options check
      $MacGPG2/bin/gpg2 --gpgconf-test --options "$homedir/.gnupg/gpg.conf" || mv "$homedir/.gnupg/gpg.conf" "$homedir/.gnupg/gpg.conf.`date +%Y%m%d%H%M%S`$RANDOM"
    fi
    
    if [ -e "$homedir/.gnupg/gpg-agent.conf" ]; then
      # Remove any gpg-agent pinentry program options
      sed -i '' 's/^[ 	]*pinentry-program/#pinentry-program/g' "$homedir/.gnupg/gpg-agent.conf"
    fi
  
    if [ ! -e "$homedir/.gnupg/gpg.conf" ]; then
      if [ -e "$MacGPG2/share/gnupg/gpg-conf.skel" ]; then
        # If no options file and skeleton exists, copy over skipping
        #  first three lines
        tail -n +4 "$MacGPG2/share/gnupg/gpg-conf.skel" > "$homedir/.gnupg/gpg.conf"
        # Set correct ownership and reset permissions
        chown $uniqueID:$primarygroup "$homedir/.gnupg/gpg.conf"
        chmod og= "$homedir/.gnupg/gpg.conf"
      fi
    fi
  
  fi
done

# Kill any running copies of gpg-agent:

killall gpg-agent

# No longer rely upon start-gpg-agent, now started on demand by gpg2 as needed.

# Remove all GnuPG v2.0.16 related files
rm -f $OldMacGPG2/lib/charset.alias &> /dev/null
rm -f $OldMacGPG2/lib/gettext &> /dev/null
rm -f $OldMacGPG2/lib/gettext/hostname &> /dev/null
rm -f $OldMacGPG2/lib/gettext/project-id &> /dev/null
rm -f $OldMacGPG2/lib/gettext/urlget &> /dev/null
rm -f $OldMacGPG2/lib/gettext/user-email &> /dev/null
rm -f $OldMacGPG2/lib/libasprintf.0.0.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libasprintf.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libasprintf.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libasprintf.la &> /dev/null
rm -f $OldMacGPG2/lib/libgettextlib-0.17.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextlib.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextlib.la &> /dev/null
rm -f $OldMacGPG2/lib/libgettextpo.0.4.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextpo.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextpo.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextpo.la &> /dev/null
rm -f $OldMacGPG2/lib/libgettextsrc-0.17.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextsrc.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgettextsrc.la &> /dev/null
rm -f $OldMacGPG2/lib/libintl.8.0.2.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libintl.8.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libintl.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libintl.la &> /dev/null
rm -f $OldMacGPG2/bin/gpg-agent &> /dev/null
rm -f $OldMacGPG2/bin/gpg-connect-agent &> /dev/null
rm -f $OldMacGPG2/bin/gpg2 &> /dev/null
rm -f $OldMacGPG2/bin/gpgconf &> /dev/null
rm -f $OldMacGPG2/bin/gpgkey2ssh &> /dev/null
rm -f $OldMacGPG2/bin/gpgparsemail &> /dev/null
rm -f $OldMacGPG2/bin/gpgsm &> /dev/null
rm -f $OldMacGPG2/bin/gpgsm-gencert.sh &> /dev/null
rm -f $OldMacGPG2/bin/gpgv2 &> /dev/null
rm -f $OldMacGPG2/bin/kbxutil &> /dev/null
rm -f $OldMacGPG2/bin/scdaemon &> /dev/null
rm -f $OldMacGPG2/bin/watchgnupg &> /dev/null
rm -f $OldMacGPG2/libexec/gnupg-pcsc-wrapper &> /dev/null
rm -f $OldMacGPG2/libexec/gpg-check-pattern &> /dev/null
rm -f $OldMacGPG2/libexec/gpg-preset-passphrase &> /dev/null
rm -f $OldMacGPG2/libexec/gpg-protect-tool &> /dev/null
rm -f $OldMacGPG2/libexec/gpg2keys_curl &> /dev/null
rm -f $OldMacGPG2/libexec/gpg2keys_finger &> /dev/null
rm -f $OldMacGPG2/libexec/gpg2keys_hkp &> /dev/null
rm -f $OldMacGPG2/libexec/gpg2keys_ldap &> /dev/null
rm -f $OldMacGPG2/sbin/addgnupghome &> /dev/null
rm -f $OldMacGPG2/sbin/applygnupgdefaults &> /dev/null
rm -f $OldMacGPG2/share/doc &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/DETAILS &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples/gpgconf.conf &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples/pwpattern.list &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples/README &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples/scd-event &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/examples/trustlist.txt &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/FAQ &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/faq.html &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/HACKING &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/KEYSERVER &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/OpenPGP &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/README &> /dev/null
rm -f $OldMacGPG2/share/doc/gnupg/TRANSLATE &> /dev/null
rm -f $OldMacGPG2/share/gnupg/com-certs.pem &> /dev/null
rm -f $OldMacGPG2/share/gnupg/gpg-conf.skel &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.be.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.ca.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.cs.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.da.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.de.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.el.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.eo.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.es.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.et.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.fi.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.fr.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.gl.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.hu.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.id.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.it.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.ja.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.nb.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.pl.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.pt.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.pt_BR.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.ro.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.ru.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.sk.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.sv.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.tr.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.zh_CN.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/help.zh_TW.txt &> /dev/null
rm -f $OldMacGPG2/share/gnupg/qualified.txt &> /dev/null
rm -f $OldMacGPG2/share/info/dir &> /dev/null
rm -f $OldMacGPG2/share/info/gnupg.info &> /dev/null
rm -f $OldMacGPG2/share/info/gnupg.info-1 &> /dev/null
rm -f $OldMacGPG2/share/info/gnupg.info-2 &> /dev/null
rm -f $OldMacGPG2/share/locale/be &> /dev/null
rm -f $OldMacGPG2/share/locale/be/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/be/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/ca &> /dev/null
rm -f $OldMacGPG2/share/locale/ca/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/ca/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/cs &> /dev/null
rm -f $OldMacGPG2/share/locale/cs/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/cs/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/da &> /dev/null
rm -f $OldMacGPG2/share/locale/da/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/da/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/de &> /dev/null
rm -f $OldMacGPG2/share/locale/de/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/de/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/el &> /dev/null
rm -f $OldMacGPG2/share/locale/el/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/el/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/en@boldquot &> /dev/null
rm -f $OldMacGPG2/share/locale/en@boldquot/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/en@boldquot/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/en@quot &> /dev/null
rm -f $OldMacGPG2/share/locale/en@quot/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/en@quot/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/eo &> /dev/null
rm -f $OldMacGPG2/share/locale/eo/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/eo/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/es &> /dev/null
rm -f $OldMacGPG2/share/locale/es/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/es/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/et &> /dev/null
rm -f $OldMacGPG2/share/locale/et/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/et/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/fi &> /dev/null
rm -f $OldMacGPG2/share/locale/fi/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/fi/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/fr &> /dev/null
rm -f $OldMacGPG2/share/locale/fr/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/fr/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/gl &> /dev/null
rm -f $OldMacGPG2/share/locale/gl/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/gl/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/hu &> /dev/null
rm -f $OldMacGPG2/share/locale/hu/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/hu/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/id &> /dev/null
rm -f $OldMacGPG2/share/locale/id/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/id/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/it &> /dev/null
rm -f $OldMacGPG2/share/locale/it/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/it/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/ja &> /dev/null
rm -f $OldMacGPG2/share/locale/ja/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/ja/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/nb &> /dev/null
rm -f $OldMacGPG2/share/locale/nb/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/nb/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/pl &> /dev/null
rm -f $OldMacGPG2/share/locale/pl/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/pl/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/pt &> /dev/null
rm -f $OldMacGPG2/share/locale/pt/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/pt/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/pt_BR &> /dev/null
rm -f $OldMacGPG2/share/locale/pt_BR/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/pt_BR/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/ro &> /dev/null
rm -f $OldMacGPG2/share/locale/ro/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/ro/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/ru &> /dev/null
rm -f $OldMacGPG2/share/locale/ru/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/ru/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/sk &> /dev/null
rm -f $OldMacGPG2/share/locale/sk/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/sk/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/sv &> /dev/null
rm -f $OldMacGPG2/share/locale/sv/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/sv/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/tr &> /dev/null
rm -f $OldMacGPG2/share/locale/tr/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/tr/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_CN &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_CN/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_CN/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_TW &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_TW/LC_MESSAGES &> /dev/null
rm -f $OldMacGPG2/share/locale/zh_TW/LC_MESSAGES/gnupg2.mo &> /dev/null
rm -f $OldMacGPG2/share/man/man1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpg-agent.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpg-connect-agent.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpg-preset-passphrase.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpg-zip.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpg2.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpgconf.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpgparsemail.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpgsm-gencert.sh.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpgsm.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/gpgv2.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/scdaemon.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/symcryptrun.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man1/watchgnupg.1 &> /dev/null
rm -f $OldMacGPG2/share/man/man8 &> /dev/null
rm -f $OldMacGPG2/share/man/man8/addgnupghome.8 &> /dev/null
rm -f $OldMacGPG2/share/man/man8/applygnupgdefaults.8 &> /dev/null
rm -f $OldMacGPG2/lib/libassuan.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libassuan.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libassuan.la &> /dev/null
rm -f $OldMacGPG2/bin/dumpsexp &> /dev/null
rm -f $OldMacGPG2/bin/hmac256 &> /dev/null
rm -f $OldMacGPG2/lib/libgcrypt.11.6.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgcrypt.11.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgcrypt.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgcrypt.la &> /dev/null
rm -f $OldMacGPG2/bin/gpg-error &> /dev/null
rm -f $OldMacGPG2/lib/libgpg-error.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgpg-error.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libgpg-error.la &> /dev/null
rm -f $OldMacGPG2/lib/charset.alias &> /dev/null
rm -f $OldMacGPG2/lib/libcharset.1.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libcharset.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libcharset.la &> /dev/null
rm -f $OldMacGPG2/lib/libiconv.2.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libiconv.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libiconv.la &> /dev/null
rm -f $OldMacGPG2/lib/libksba.8.9.6.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libksba.8.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libksba.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libksba.la &> /dev/null
rm -f $OldMacGPG2/lib/libusb-1.0.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libusb-1.0.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libusb-1.0.la &> /dev/null
rm -f $OldMacGPG2/lib/libusb-0.1.4.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libusb.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libusb.la &> /dev/null
rm -f $OldMacGPG2/lib/libpth.20.0.27.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libpth.20.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libpth.dylib &> /dev/null
rm -f $OldMacGPG2/lib/libpth.la &> /dev/null
rm -fr /usr/local/libexec/pinentry-mac.app &> /dev/null
rm -fr /Applications/start-gpg-agent.app &> /dev/null
rm -f /Library/LaunchAgents/com.sourceforge.macgpg2.gpg-agent.plist &> /dev/null

# Add symlinks in $OldMacGPG2/bin for any hardwired programs as necessary

[ -d $OldMacGPG2/bin/ ]     || mkdir $OldMacGPG2/bin/
[ -f $OldMacGPG2/bin/gpg ]  || ln -s $MacGPG2/bin/gpg2 $OldMacGPG2/bin/gpg
[ -f $OldMacGPG2/bin/gpg2 ] || ln -s $MacGPG2/bin/gpg2 $OldMacGPG2/bin/gpg2

exit 0
